name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
assignees:
  - mamahoos
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      placeholder: Currently, users cannot ...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false
